os:
  - linux

dist: trusty

language: node_js
node_js: 8

cache: yarn

install:
  - npm install yarn -g
  - yarn

jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: test
      script: yarn test:ci
