service: netlify-travis-proxy

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    TRAVIS_ACCESS_TOKEN: ${env:TRAVIS_ACCESS_TOKEN}
    TARGET_REPO: ${env:TARGET_REPO}
    GITHUB_OAUTH_TOKEN: ${env:GITHUB_OAUTH_TOKEN}

functions:
  ghStatusManager:
    handler: src/gh-status-manager.handler

    events:
      - http:
          path: github-status
          method: post
  travisCaller:
    handler: src/travis-caller.handler

    events:
      - http:
          path: travis-caller
          method: post
