service: netlify-travis-proxy

provider:
  name: aws
  runtime: nodejs6.10
  environment:
    TRAVIS_ACCESS_TOKEN: ${file(./config.${self:provider.stage}.json):TRAVIS_ACCESS_TOKEN}
    TARGET_REPO: ${file(./config.${self:provider.stage}.json):TARGET_REPO}
    GITHUB_OAUTH_TOKEN: ${file(./config.${self:provider.stage}.json):GITHUB_OAUTH_TOKEN}

functions:
  ghStatusManager:
    handler: src/gh-status-manager.handler

    events:
      - http:
          path: github-status
          method: post
  travisCaller:
    handler: src/travis-caller.handler

    events:
      - http:
          path: travis-caller
          method: post
